---
- name: Upgrade all packages
  apt:
    name: "*"
    state: latest

- name: Install base packages
  apt:
    name:
      - aspell
      - aspell-en
      - autoconf
      - build-essential
      - clang-format
      - cmake
      - curl
      - direnv
      - editorconfig
      - feh
      - flatpak
      - gettext
      - git
      - glslang-dev
      - glslang-tools
      - gnuplot
      - gnutls-bin
      - gnutls-dev
      - graphviz
      - install
      - libacl1-dev
      - libdbus-1-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libgccjit-11-dev
      - libgif-dev
      - libharfbuzz-dev
      - libjansson-dev
      - libjansson4
      - libmagickwand-dev
      - libncurses-dev
      - libnss3-tools
      - libpcsc-perl
      - libpcsclite-dev
      - libpcsclite1
      - libssl-dev
      - libtinfo-dev
      - libtool
      - libtool-bin
      - libtree-sitter-dev
      - libx11-dev
      - libxaw7-dev
      - libxcb-xfixes0-dev
      - libxcb-xinerama0-dev
      - libxinerama-dev
      - libxkbcommon-dev
      - mpv
      - nala
      - ninja-build
      - nodejs
      - npm
      - openjdk-19-jdk
      - opensc
      - pcsc-tools
      - pkg-config
      - procps
      - python3
      - python3-pip
      - sbcl
      - shellcheck
      - shfmt
      - sqlite3
      - steam-devices
      - stow
      - texinfo
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-latex-base
      - texlive-latex-extra
      - tidy
      - tmux
      - unzip
      - wl-clipboard
      - xclip
      - xdotool
      - zsh
    state: installed

- name: Install Rust packages
  shell: |
    [ -f ~/.cargo/env ] && source $HOME/.cargo/env
    cargo install bottom lsd rm-improved fd-find bat zoxide cargo-update \
      tree-sitter-cli editorconfig starship myfly alacritty delta
    cargo install ripgrep --features pcre2
    cargo install --locked yazi-fm yazi-cli

- name: Create ~/Dev if it does not exist
  ansible.builtin.file:
    path: ~/Dev
    state: directory
    mode: "0755"

- name: Create ~/Work if it does not exist
  ansible.builtin.file:
    path: ~/Work
    state: directory
    mode: "0755"

- name: Install OMZ
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install Tmux Package Manager
  shell: git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm

- name: Install Neovim from source
  shell: |
    git clone https://github.com/neovim/neovim ~/Dev/neovim
    cd ~/Dev/neovim
    make CMAKE_BUILD_TYPE=Release
    sudo make install
  when: install_neovim
