---
- name: Create Docker group
  group:
    name: docker
    state: present

- name: Setup {{ local_user }} user
  user:
    name: "{{ local_user }}"
    home: /home/{{ local_user }}
    groups: wheel,docker
    append: yes

- name: Allow wheel group to sudo without a password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  when: local_user_passwordless_sudo
